### ISSUE TITLE
Cannot find path 'C:\Program Files\nuget\packages'

### ISSUE THREAD

**Issue by lilei105** [DarwinJS/ChocoPackages#36] opened 2017-06-16 02:20 UTC
I'm following Install Scenario 2: Non-Chocolatey Using PSH 5 PackageManagement and got below error.
Shouldn't it be 'C:\Program Files (x86)'?
![darwin](https://user-images.githubusercontent.com/6941475/27209280-6cffd280-527d-11e7-9e80-f3a55385261a.png)

**Comment by DarwinJS** [comment] 2017-06-16 03:09
@lilei105 - could you please give more details about your environment?

What version of Windows?  
Is it 32-bit or 64-bit Windows?
Did you launch this as as 32-bit script on a 64-bit system?
Do you find the "nuget" folder under c:\program files (x86) ?

%ProgramFiles% will be "C:\Program Files" for a 32-bit process on a 32-bit system OR a 64-bit Process on a 64-bit System.  

%ProgramFiles% will be "C:\Program Files (x86)" for 32-bit process on a 64-bit System.

**Comment by DarwinJS** [comment] 2017-07-21 11:58
I am closing this due to not receiving additional root cause feedback information.

**Closed by DarwinJS** 2017-07-21 11:58 UTC
