### ISSUE TITLE
[openssh] Cannot install via Chocolatey because of error: "The term 'Get-FileHash' is not recognized..."

### ISSUE THREAD

**Issue by C-Duv** [DarwinJS/ChocoPackages#18] opened 2016-10-26 10:33 UTC
Using chocolatey v0.10.3 on Windows 7 SP1 with PowerShell v2.0 I cannot install the [`openssh`](https://chocolatey.org/packages/openssh) package, I have the following error:

> ERROR: The term 'Get-FileHash' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Steps to reproduce**

Command:
```Batch
choco install -y openssh -params="/SSHServerFeature"
```

Returns:

> Chocolatey v0.10.3
> Installing the following packages:
> openssh
> By installing you accept licenses for the packages.
> 
> openssh v0.0.2.0 [Approved]
> openssh package files install completed. Performing other installation steps.
> Running on: Windows 7 Professional, (Professional)
> 
> ********************************************************************************
> This package can install Win32-OpenSSH on Nano - See the following for details:
> https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/readme.md
> ********************************************************************************
> 
> /SSHServerFeature was used, including SSH Server Feature.
> /SSHAgentFeature is also automatically enabled when using /SSHServerFeature.
> Probing for possible conflicts with SSHD server to be configured on port 22 ...
> ERROR: The term 'Get-FileHash' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
> The install of openssh was NOT successful.
> Error while running 'C:\ProgramData\chocolatey\lib\openssh\tools\chocolateyinstall.ps1'.
>  See log for details.
> 
> Chocolatey installed 0/1 packages. 1 packages failed.
>  See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
> 
> Failures
>  - openssh (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\openssh\tools\chocolateyinstall.ps1'.
>  See log for details.

I have no issue installing other packages that uses checksums to verify installer (eg. [`pdfsam.install`](https://chocolatey.org/packages/pdfsam.install)).

**Comment by DarwinJS** [comment] 2016-10-26 11:27
Thanks for your report.
This has been addressed in a new package, just released, version 0.0.2.20161026.

Please re-open if this is still a problem.

**Closed by DarwinJS** 2016-10-26 11:27 UTC

**Comment by C-Duv** [comment] 2016-10-26 11:49
Works now (tested on two machines):
`choco install -y openssh -version 0.0.2.20161026 -params="/SSHServerFeature"`

Thanks.

**Comment by DarwinJS** [comment] 2016-10-26 11:49
Great!  Thanks for reporting it.

**Comment by dragon788** [comment] 2016-10-26 15:44
This probably needs to depend on Powershell package to get Powershell 5,
though I believe get-filehash possibly came in Powershell 3 or 4. The other
alternative would be to use the checksum.exe that comes with Chocolatey to
maintain it's backwards compatible to Powershell 2.

**Comment by C-Duv** [comment] 2016-10-26 15:58
Chocolatey itself is capable of compute file hashs on Powershell v2: the example I gave with package `pdfsam.install` is passing hash value to builtin method `Install-ChocolateyPackage`, asking him to perform the download and comparison.

**Comment by DarwinJS** [comment] 2016-10-26 16:12
Sorry to create confusing - this checksum check was being done outside chocolate's built in support because the files are internal.  It was designed to be just a little extra insurance for those who are used to looking for checksums because Choco default behavior seems to be not to check checksums on internal files nor indicate that the files were internal.
