### ISSUE TITLE
Install does not work when executed as NT AUTHORITY\SYSTEM

### ISSUE THREAD

**Issue by gravcat** [DarwinJS/ChocoPackages#41] opened 2017-09-06 06:04 UTC
I am leveraging Custom Script Extension via Microsoft Azure to execute a script on a host. One of which has a call to run your (awesome) Win32-OpenSSH package to install.

Unfortunately it fails, as the temp file is not set in the SYSTEM user's environment, thus `GetTempFileName()` does not work. It's possible to simply create your own temp file, this may be a more reasonable approach to handle more edge cases.

http://powershell-guru.com/powershell-tip-36-create-a-temporary-file/

**Comment by DarwinJS** [comment] 2017-09-06 12:50
@gravcat - thanks for reporting.

I've had this issue reported once before and I found that:

1. GetTempFileName() does indeed work properly under regular system account execution using psexec.exe - it redirects to c:\windows\temp - so there is something additional at play with either the DSC and/or Azure implementations of running the package.
2. the proposed remedy I tried from the previous report did not work under Nano.

Here is the record of the previous issue that shows my testing of the regular system account context being successful: https://github.com/DarwinJS/ChocoPackages/issues/39

Since this execution scenario is decidedly different than a standard SYSTEM account execution - could you do me a favor and code up a write to %windir%\temp\something and then run it in your scenario?

This way I can know [a] that %WINDIR%\temp is a valid reference in YOUR explicit execution context and that [b] you can write to it.

If it works I will write a custom temp file routine that uses that folder AND ensures that whatever it picks is unique (does not already exist).

Thanks.

**Comment by gravcat** [comment] 2017-09-06 14:52
Oh, how interesting. Thanks for sharing this, I'll give it a try and let you know what it looks like.

**Comment by DarwinJS** [comment] 2017-09-07 21:15
@gravcat - I was wondering if you'd had an opportunity to do this testing?  I am holding up the packaging for the 0.0.20.0 release in hopes of working this in.

**Comment by DarwinJS** [comment] 2017-09-08 01:44
Better yet, I've worked it into the next package with a simple creation of a temp file in c:\windows\temp. 
 Since I can only put a package to chocolatey once, I have put it on my test feed where you can run it from to see if it works.

Here is the regular command that you can adapt for your situation:
```
cinst -y openssh -params '"/SSHServerFeature"' -source https://www.myget.org/F/chocotesting/api/v2/
```

**Comment by DarwinJS** [comment] 2017-09-11 12:21
v0.0.20.0 of the openssh package should fix this - please reopen this issue if you find it is still a problem.

**Comment by gravcat** [comment] 2017-09-11 14:47
Hey @DarwinJS,

I've been out of town and beyond that busy with competing priority projects too. I read about your 0.0.20.0 release this morning and re-ran the installation with it.

I don't see anything complaining about those temp files, however there are these still:

```Installing OpenSSH via chocolatey

Switching to OpenSSH-Win64 dir
Current directory is C:\Program Files\OpenSSH-Win64
Running install-sshd.ps1
PS>TerminatingError(Add-Type): "Could not find a part of the path 'C:\Windows\system32\config\systemprofile\AppData\Local\Temp\ijscah1p.tmp'."
Add-Type : Could not find a part of the path 'C:\Windows\system32\config\systemprofile\AppData\Local\Temp\ijscah1p.tmp'.
At C:\Program Files\OpenSSH-Win64\install-sshd.ps1:233 char:14
+ ...    $types = Add-Type $definition -ref $references -WarningAction Sile ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.PowerShell.Commands.AddTypeCommand
Add-Type : Could not find a part of the path
'C:\Windows\system32\config\systemprofile\AppData\Local\Temp\ijscah1p.tmp'.
At C:\Program Files\OpenSSH-Win64\install-sshd.ps1:233 char:14
+ ...    $types = Add-Type $definition -ref $references -WarningAction Sile ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-Type], DirectoryNotFoundE
   xception
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException,Microsoft.P
   owerShell.Commands.AddTypeCommand




Unable to find type [MyLsaWrapper.LsaWrapperCaller].
At C:\Program Files\OpenSSH-Win64\install-sshd.ps1:247 char:5
+     [MyLsaWrapper.LsaWrapperCaller]::AddPrivilege($Account, $Privileg ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (MyLsaWrapper.LsaWrapperCaller:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
Unable to find type [MyLsaWrapper.LsaWrapperCaller].
At C:\Program Files\OpenSSH-Win64\install-sshd.ps1:247 char:5
+     [MyLsaWrapper.LsaWrapperCaller]::AddPrivilege($Account, $Privileg ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (MyLsaWrapper.LsaWrapperCaller
   :TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Unable to find type [MyLsaWrapper.LsaWrapperCaller].
At C:\Program Files\OpenSSH-Win64\install-sshd.ps1:247 char:5
+     [MyLsaWrapper.LsaWrapperCaller]::AddPrivilege($Account, $Privileg ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (MyLsaWrapper.LsaWrapperCaller:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
Unable to find type [MyLsaWrapper.LsaWrapperCaller].
At C:\Program Files\OpenSSH-Win64\install-sshd.ps1:247 char:5
+     [MyLsaWrapper.LsaWrapperCaller]::AddPrivilege($Account, $Privileg ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (MyLsaWrapper.LsaWrapperCaller
   :TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

sshd and ssh-agent services successfully installed
Running ssh-keygen to generate host keys

Running Set-SSHKeyPermissions
. : The term 'C:\Program Files\OpenSSH-Win64\Set-SSHKeyPermissions.ps1' is not recognized as the name of a cmdlet, 
function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the 
path is correct and try again.
At C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.9\Downloads\0\bootstrap-w10-orch.ps1:44 char:3
+ . "C:\Program Files\OpenSSH-Win64\Set-SSHKeyPermissions.ps1"
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...Permissions.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
. : The term 'C:\Program Files\OpenSSH-Win64\Set-SSHKeyPermissions.ps1' is not
recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At C:\Packages\Plugins\Microsoft.Compute.CustomScriptExtension\1.9\Downloads\0\
bootstrap-w10-orch.ps1:44 char:3
+ . "C:\Program Files\OpenSSH-Win64\Set-SSHKeyPermissions.ps1"
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...Permissions.p
   s1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException```

I'm also working with Microsoft in annoyance with their Custom Script Extension feature.

**Comment by gravcat** [comment] 2017-09-11 14:53
I don't think I have the ability to re-open. Sorry for multi-comment spam.

**Comment by DarwinJS** [comment] 2017-09-13 14:16
This does not look like my code => install-sshd.ps1, nor do the individual lines appear to be anything from the chocolatey package.

You do not need to run any of the openssh utility scripts after the chocolatey package.

Can you share the exact lines of code you are invoking to install this?

**Comment by DarwinJS** [comment] 2017-09-14 00:42
@gravcat - the chocolately package was designed to perform all the functions of install-sshd.ps1.  If you are running it to fix up some type of problem - could you please describe that problem so I can attempt to reproduce it?

**Comment by gravcat** [comment] 2017-09-14 00:46
Hmm, I thought for sure that `install-sshd.ps1` was invoked from the openssh utility scripts as part of your installer package. Perhaps I'm just confused about this process now.

I'll try to just run the chocolatey package on it's own and come back with some clarity on the subject.

**Comment by DarwinJS** [comment] 2017-09-14 01:05
No, the OpenSSHUtils.psm1 and it's associated scripts are here: https://github.com/PowerShell/Win32-OpenSSH/tree/L1-Prod/contrib/win32/openssh

If you search for install-sshd.ps1 in that repo - it does not show up in any of the OpenSshUtils files (it only in a few scripts used for the CI build)

Someone did report here: https://chocolatey.org/packages/openssh#comment-3516378532 that they feel they have to run install-sshd.ps1 after the chocolatey package. I researched it and did find one command that was in that script that was not in the chocolatey package.  I have added it and have pushed 0.0.20.20170913. (not done moderation quite yet - you can directly reference the version number to pull it before moderation is done)

However, I do not know the exact use cases where this was needed, so I don't have anyway to test if it fixes the problems that some seem to have been running install-sshd.ps1 to solve.

**Comment by DarwinJS** [comment] 2017-10-18 10:58
@gravcat - are you still experiencing this problem with the latest version?

**Comment by kha7** [comment] 2017-11-15 16:30
Hi, I might have run into this issue also. I create a Custom Script Extension in Azure. It downloads and executes a ps1 file which runs:

Set-ExecutionPolicy Unrestricted -Force
Invoke-Expression ((New-ObjectSystem.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
choco install -y openssh -params '"/SSHServerFeature"'

The sshd service does install, but cannot start. When I try and start it:

"Error 1297: A privilege that the service requires to function properly does not exist in the service account configuration. You may use the Services Microdoft Management Console (MMC) snap-in (services.msc) and the Local Security Settings MMC snap-in (secpol.msc) to view the service configuration and the account configuration."

I followed the workaround steps found in https://github.com/PowerShell/Win32-OpenSSH/issues/770:
Open control panel and navigate to
Administrative Tools > Local Security Policy > Local Policies > User Rights Assignment.
Double click Replace a Process Level Token
Add NT Service\SSHD

After adding the account, and trying to start the service it throws another error:
"Error 1067: The process terminated unexpectedly"

I can get this to work by logging into the server and running the ps1 file manually so I know that works.

@gravcat You mention a workaround by creating a temp file. Can you post steps for this?

**Comment by DarwinJS** [comment] 2017-11-15 18:38
@kha7 - as mentioned earlier in this thread a temp folder work around was worked into version 0.0.20.0 - but no one has confirmed it either fixed it or forwarded information with additional diagnostic data.

This line should be giving that special right to "NT Service\SSHD" and you should see logging confirming it in the main script output: https://github.com/DarwinJS/ChocoPackages/blob/master/openssh/tools/chocolateyinstall.ps1#L591

**Comment by kha7** [comment] 2017-11-15 21:19
Hi @DarwinJS  - I can confirm that "Replace a process level token" setting does not include "NT Service\SSHD" account when installing OpenSSH with Azure Custom Script Extensions. I just tried it again now.

Is there anything I can post to help troubleshoot this issue?

**Comment by DarwinJS** [comment] 2017-11-15 21:41
Can you post the chocolatey log to a gist?

Also can you verify whether that account was successfully added to SeServiceLogonRight by the installation?

**Comment by kha7** [comment] 2017-11-16 01:28
Hi DarwinJS. Thanks for your help.

Here is the Chocolatey log: https://gist.github.com/kha7/4fd139c4653e55f1ba5575e6851b4015
OpenSSH install starts at line 2972. I did find from the log that OpenSSH does not install successfully.

When I look Log on as a service, I see "NT Service\ssh-agent" is there, but I don't see "NT Service\sshd".

**Comment by DarwinJS** [comment] 2017-11-16 13:29
@kha7 - that was super useful thanks!  I have opened an issue in the main PowerShell repo as this would appear to be the activities of OpenSSHUtils.psm1 - which ships with openssh.

https://github.com/PowerShell/PowerShell/issues/5479

**Comment by ebekker** [comment] 2018-03-21 04:13
I seem to be running into a related issue, I too am failing to install OpenSSH.  My environment is a Windows 2016 server in AWS.  I'm using the cChoco package in DSC.

It seems that the last activity was focusing on this issue in the context of Custom Script Extensions in Azure, which is not my situation.  Looks like there hasn't been much activity on this issue for the last few months, either here or in PowerShell/PowerShell#5479 -- I was wondering if anyone had any workarounds?

If any more details or log samples would be helpful, let me know.

**Comment by DarwinJS** [comment] 2018-03-21 10:25
@ebekker - I think this specific issue is fixed by now.  Please post your logs to gist.

**Comment by ebekker** [comment] 2018-03-21 13:22
I've posted the log excerpt and the relevant portions of the related DSC configuration to [this gist](https://gist.github.com/ebekker/60afa998f1a540d38100cbfacb97ad33).

The whole DSC configuration also has a number of other configuration steps before (and a few after) the actual SSH install -- if you think that could be related or helpfule, I can provide the whole thing, or I could even run the SSH install in isolation.

In the log file, I think the problem that's related to similar issues in prior comments of this ticket is line `1480` which indicates an issue with the temp file path under the context of the local system account.

**Comment by DarwinJS** [comment] 2018-04-30 11:51
@ebekker - the log you posted does not reveal the underlying error.  Maybe there is a way to pass full verbose debugging switches to chocolatey under DSC?

Also, at this point the package had changed quite a bit - so you might want to simply try again with the latest to confirm that it is still broken.

**Comment by ebekker** [comment] 2018-04-30 11:54
Thanks, I'll try to update and run with the latest in the next few days.

In the meantime, if anyone else is running into this issue, I was able to get around the issue a few weeks back by simply creating a temporary local admin account and switching execution of the install under that account.

**Comment by DarwinJS** [comment] 2018-04-30 12:03
@ebekker - ok thanks for the work around.  Have you ever run into any messages like @gravcat posted to start this issue?

His case smells like a bug where the .NET call for a temporary file name was not working under SYSTEM account - but I thought Microsoft had made code changes to avoid that call.  (The OpenSSH installer was calling a standard Microsoft powershell module to setup permissions.)

**Comment by ebekker** [comment] 2018-04-30 12:32
Woops!  Sorry, I thought I did already mention in the ticket -- yes, that is exactly the issue, the installer cannot resolve the location to put the temporary files when running under SYSTEM.

**Comment by ebekker** [comment] 2018-05-24 04:09
Looks like this is no longer an issue, I've run through without using the *local admin kludge* and everything installed correctly, thanks!

**Comment by DarwinJS** [comment] 2018-05-24 10:52
@ebekker  - thanks for circling back.  I will close this as fixed since I know that specific fixes were put into the openssh utils to account for the problem.

**Closed by DarwinJS** 2018-05-24 10:52 UTC

**Comment by Rodalli** [comment] 2019-02-13 00:25
@DarwinJS This issue appears to have returned! I'm trying to install openssh v.1.0.0.20180201 (v.7.9.0.1) by invoking the following command as SYSTEM:

`choco install openssh -params '"/SSHServerFeature /SSHLogLevel:INFO"' -y`

When I do, I get the same ERROR referencing a file in C:\Windows\System32\config\systemprofile\AppData\Local\Temp\ that doesn't exist. Indeed, the Temp folder at this path doesn't even exist.

If I run it as any other user, the install works without issue.

**Comment by DarwinJS** [comment] 2019-02-13 00:29
@Rodalli - you will need to submit your issue directly to the OpenSSH project here: https://github.com/PowerShell/Win32-OpenSSH/issues because the fix went into the OpenSSHUtils.psm module they publish with openssh.

**Comment by Rodalli** [comment] 2019-02-13 00:39
@DarwinJS Roger that. I will submit an issue with that project. Thank you!
